version: '2'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/ssl:/etc/ssl/
      - ./build:/usr/share/nginx/html
    ports:
      - "7844:7844"
      - "7845:7845"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"